### PR TITLE
added a gemini bot for user interaction

### PR DESCRIPTION
**Pull request by powerstone666**
added a chatbot based on Gemini API  with this users can easily ask questions and queries related to shoes or compare different brands etc....

replace vite_key with gemini actually API which you can get for free on google gemini website.

here's the demo video of it.
https://github.com/harshalhonde21/EcommerceSpectastyle/assets/142788077/d062f67b-db19-4ea0-ab48-782b8cad66b3

### CODE REVIEW

**Comment by powerstone666** [comment]
add gssoc label to it

**Comment by harshalhonde21** [comment]
give me whole procedure go get by gemini api key

**Comment by powerstone666** [comment]
https://aistudio.google.com/app/apikey.  In this website you will get it just login and click on get api key and add level 2 to it.

**Comment by powerstone666** [comment]
Hyy merge the PR

**Comment by harshalhonde21** [comment]
It takes time to do this so because of time to login and all stuff is not having currently but it will merge after some time as contribution is good

**Pull request closed without merging**
