### PR TITLE
Resolves issue #15 (responsiveness of about page)

### PR DESCRIPTION
**Pull request by SaranshBangar**
Resolves issue #15 

Before ->

WhatsApp Image 2024-05-10 at 08 19 55_915056dd

After ->

WhatsApp Image 2024-05-10 at 12 27 42_c1de993c

Changes made -> Added another media query in About.css

Request -> Sir, if possible, please merge this PR after 7:00 pm IST

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves #15

**Comment by harshalhonde21** [comment]
> Resolves #15

great work @SaranshBangar, can you see with the [issue ](https://github.com/harshalhonde21/EcommerceSpectastyle/issues/12)

**Comment by SaranshBangar** [comment]
> > Resolves #15
> 
> great work @SaranshBangar, can you see with the [issue ](https://github.com/harshalhonde21/EcommerceSpectastyle/issues/12)

Sure sir, give me around 30 - 40 mins and I will raise the PR for that

**Comment by SaranshBangar** [comment]
@harshalhonde21 Sorry to disturb you sir, but can please add proper labels on this PR as it would affect my final scores

**Pull request merged**
