### PR TITLE
solves issue #229

### PR DESCRIPTION
**Pull request by AMISH-KHAN**
solves issue #229 

I have added correct username and also made the page responsive

https://github.com/harshalhonde21/EcommerceSpectastyle/assets/123164129/a9a918a5-e7be-4960-bb1f-9d7f0fa7db47

### CODE REVIEW

**Comment by AMISH-KHAN** [comment]
@harshalhonde21  please review it!!

**Comment by harshalhonde21** [comment]
image


margin of that container is not same do with this

**Comment by AMISH-KHAN** [comment]
@harshalhonde21 okay I will align all the container to the centre

**Comment by AMISH-KHAN** [comment]
@harshalhonde21 is this fine

image

**Comment by AMISH-KHAN** [comment]
> @harshalhonde21 is this fine
> 
> image

@harshalhonde21 please look into it

**Comment by harshalhonde21** [comment]
take the pull/sync first then i will do with this, by the way contribution is good

**Review by harshalhonde21 — APPROVED** [review]

**Comment by AMISH-KHAN** [comment]
@harshalhonde21  please review it

**Comment by harshalhonde21** [comment]
great

**Pull request merged**
