### PR TITLE
Corrected the linking of page on removal of items from cart

### PR DESCRIPTION
**Pull request by kesharwaniyanshi**
Earlier on removing any item from cart loaded the product page which might be annoying for the user .
I fixed the issue by removing the navigate command and instead just refreshing the cart page.

### CODE REVIEW

**Comment by harshalhonde21** [comment]
The page is reloading whole you remove changing route but the worst behavior after using react also why you are reloading whole page

**Comment by harshalhonde21** [comment]
setTimeout(() => {
        window.location.reload();
      }, 1000);
      
      
      what is reason behing at timeout here ??????????

**Comment by kesharwaniyanshi** [comment]
Timeout does not have a specific reason ,simply reloading the page would work.

> setTimeout(() => { window.location.reload(); }, 1000);
> 
> ```
>   what is reason behing at timeout here ??????????
> ```

**Comment by kesharwaniyanshi** [comment]
> The page is reloading whole you remove changing route but the worst behavior after using react also why you are reloading whole page

earlier navigate(/product) was used .If i use navigate(/cart) instead so still the page does not refresh after removing any item. After selecting remove it will display Item removed successfully but the item item card still shows in the card and is removed if i manually refresh the page.So instead of manually refreshing i used the reload so that after removing the page automatically reloads and user doesn't have to do it.

**Comment by harshalhonde21** [comment]
Don't do this bad approach instead use any hook of react to do this

**Comment by kesharwaniyanshi** [comment]
> Don't do this bad approach instead use any hook of react to do this

Okay i have changed my approach .Please review it .

**Comment by harshalhonde21** [comment]
great of now but take the pull many of the functionality is not update take pull to merge all upcoming functionality before you raise the pr

**Comment by kesharwaniyanshi** [comment]
I have made the required changes . Now you can merge it.

**Comment by harshalhonde21** [comment]
can you take pull of website and commit once again

**Comment by kesharwaniyanshi** [comment]
Is it ok now?

**Comment by kesharwaniyanshi** [comment]
Please merge the PR if its ok.

**Comment by harshalhonde21** [comment]
great @kesharwaniyanshi

**Pull request merged**
