### PR TITLE
feat: Add functionality to increase user visit count

### PR DESCRIPTION
**Pull request by abhiperfect**
This commit implements the functionality to increase the count of user visits. API endpoints have been provided for hitting locally to reflect changes in the database.

### CODE REVIEW

**Comment by harshalhonde21** [comment]
Do one thing the pull first of updated website and then give the PR your contribution is great to see

**Comment by harshalhonde21** [comment]
> > Do one thing the pull first of updated website and then give the PR your contribution is great to see
> 
> should i pull from your repo??

take the pull first then Raise the PR

**Comment by harshalhonde21** [comment]
> > > Do one thing the pull first of updated website and then give the PR your contribution is great to see
> > 
> > 
> > should i pull from your repo??
> 
> take the pull first then Raise the PR

the conflict should be resolve of backend/index.js

**Comment by abhiperfect** [comment]
> > > > Do one thing the pull first of updated website and then give the PR your contribution is great to see
> > > 
> > > 
> > > should i pull from your repo??
> > 
> > 
> > take the pull first then Raise the PR
> 
> the conflict should be resolve of backend/index.js

ok doing it

**Pull request closed without merging**
