### PR TITLE
Size mention

### LINKED ISSUE #363: Feat: Provision to add shoe size
### Describe the feature

Add a shoe size chart compatible for all users.
image
Kindly assign this issue to me

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkhilaSunesh**
## Related Issue
fixes #363 

## Description
add shoe size to the products

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by harshalhonde21** [comment]
the code is not actually I check that you pass shoe size with api but the api doesn't take the particular term so why you put that

**Comment by AkhilaSunesh** [comment]
I have made in changes in Frontend/src/Components/ProductDetail.jsx

**Comment by harshalhonde21** [comment]
> I have made in changes in Frontend/src/Components/ProductDetail.jsx

read what i says firstly

**Comment by harshalhonde21** [comment]
closed as not done correctly ask for changes not repied 2 days over

**Pull request closed without merging**
