### PR TITLE
added profilepic field in userSchema

### PR DESCRIPTION
**Pull request by p00jitha**
Added profilepic field in userSchema to store user's profile photo.
Screenshot 2024-05-12 120047

### CODE REVIEW

**Comment by harshalhonde21** [comment]
It is just you are adding the new field in user schema now what about this where it will store make the whole functionality that user will take the input as file type then store in [Cloudinary](https://cloudinary.com/) and then it will store in profile section

**Comment by p00jitha** [comment]
I will create public folder in bakend folder it will store user profile pic's . I'm not using cloudinary.

**Comment by p00jitha** [comment]
If we won't include profilepic field then we can't store data in database

**Comment by p00jitha** [comment]
Screenshot 2024-05-12 201613
This is  the code

**Comment by harshalhonde21** [comment]
I need profile pic field in db and you are added that in this branch but then also anything is not running correctly??

**Comment by p00jitha** [comment]
@harshalhonde21  when ever we are making PR  vercel is deploying our code and it's showing preview that's ok. Then what about backend it is deployed in render , it should also deploy and test know. That's why it's not working. 
const response = await fetch(
          "https://ecommerce-backend-0wr7.onrender.com/ecommerce/user/signup",
          {
            method: "POST",
            body:formData,
          }
        );
here, https://ecommerce-backend-0wr7.onrender.com this is your deployed backend url, when we made any changes again the backend should deploy then only our code will work fine. To avoid this conflicts you should add profilepic field in usermodel and again deploy your backend then it works fine. If you don't do that no one can add this feature. Plz check it. I hope you understand. And no need to merge this PR instead of this you add profilepic field in usermodel and deploy your backend code.

**Review by Apurv7777 — COMMENTED** [review]
When I go through the way of storing images through **multer**, I found that there is a 
- Disadvantage:
     - Storing user's data on the server might be a security / privacy issue.

**Comment by harshalhonde21** [comment]
The multer is great choice but @p00jitha I want to save that photos on cloud use cloudinary for this

**Review by harshalhonde21 — CHANGES_REQUESTED** [review]
do with the cloudinary to store data in cloud of images

**Comment by Jhonsnowwwwww** [comment]
@harshalhonde21  i acn do it with using cloudinary and adding cloudinary.js file can u pease assign me this task i can do it wth in two hours please assign me this task

**Comment by harshalhonde21** [comment]
> @harshalhonde21 i acn do it with using cloudinary and adding cloudinary.js file can u pease assign me this task i can do it wth in two hours please assign me this task

great @Jhonsnowwwwww do with this

**Comment by Jhonsnowwwwww** [comment]
Thnaks a lot @harshalhonde21 can u please assign this task to me i have started working on it

**Comment by Jhonsnowwwwww** [comment]
hey @harshalhonde21 can u give me your cloudinary account credentials which u want to use in project or should  i  use mine account of cloudinary please tell me what should i do u can connect with me on discord Yash Gupta#3535 so we can discuss about it and i have one more thing to discuss how we can make our code base and our project have industry level code i mean how can we make this project well organised and  clean so to increase the readability of our codebase

**Comment by harshalhonde21** [comment]
done as completed

**Pull request closed without merging**
