### PR TITLE
solved issue #254

### PR DESCRIPTION
**Pull request by Prateek579**
solved issue #254 

1 :- Password Reset Section: Add a new section to the application where users can request a password reset. This should involve a form where users can input their email addresses to receive secret number.

2 :- Nodemailer Integration: Use Nodemailer to send a secret number to the user's registered email address.

Screenshot 2024-05-24 121538
Screenshot 2024-05-24 121813

### CODE REVIEW

**Comment by harshalhonde21** [comment]
actually the contribution is very big I need to examine the code properly for now to come error in production so wait untill that

**Comment by Prateek579** [comment]
@harshalhonde21  could you please change the level?

**Comment by Prateek579** [comment]
@harshalhonde21  please change the level and review it,

**Comment by harshalhonde21** [comment]
ohk let you know that once again do with the change take the latest pull from website use production api not our local okh and come up with that

**Pull request closed without merging**
