### PR TITLE
Feat: adding favicon icon

### PR DESCRIPTION
**Pull request by solanki505**
issue #125
Screenshot 2024-05-12 132601

### CODE REVIEW

**Comment by solanki505** [comment]
@harshalhonde21 sir do you like  the icon I have given or should I change it???
Screenshot 2024-05-12 132601

**Comment by harshalhonde21** [comment]
Great job @solanki505, you can contact me in linkedin for the design of frontend if you are interested

**Comment by solanki505** [comment]
ok sir Thanks for your review

**Comment by solanki505** [comment]
@harshalhonde21 sir please assign me otherwise it is not showing in my profile? Does without assigning Score shall be added under GSSOC'24?

**Comment by solanki505** [comment]
@harshalhonde21 sir please assign the pr to me, otherwise the score is not added to my leader board in GSSOC.

**Pull request merged**
