### PR TITLE
feat: Add functionality to increase user visit count

### PR DESCRIPTION
**Pull request by abhiperfect**
[conflict resolved] This commit implements the functionality to increase the count of user visits. API endpoints have been provided for hitting locally to reflect changes in the database.

### CODE REVIEW

**Comment by abhiperfect** [comment]
@harshalhonde21 please have a look!

**Comment by harshalhonde21** [comment]
> @harshalhonde21 please have a look!

Great

**Comment by harshalhonde21** [comment]
why the user count is not incrementing??

**Comment by abhiperfect** [comment]
> why the user count is not incrementing??

let me check, but before merged it was working fine.

**Comment by abhiperfect** [comment]
> why the user count is not incrementing??

now this is working sir!, sir this task is completed??

**Comment by harshalhonde21** [comment]
Yaaa, cool👍

**Comment by abhiperfect** [comment]
Hello sir, could you please provide a label and specify the level for this task under "GSSCO '24"?

**Pull request merged**
