### PR TITLE
Fixed issue #413 feat:smoothscroll-added

### PR DESCRIPTION
**Pull request by rahul-shrivastav**
## Related Issue
None

## Description
Added smooth scroll effect to the website

## Type of PR

- [x ] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/harshalhonde21/EcommerceSpectastyle/assets/114675655/884bf3d3-b87f-4b22-a0a4-8a45f612c6d3

## Checklist:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by harshalhonde21** [comment]
this can also done by up arrow button use any library of scroll that when scrool with scrooling button it should very smooth not stuck after one scroll

**Comment by rahul-shrivastav** [comment]
will this get merged ? if not then what should i change , please give example of the button thing if that needs to be implemented

**Comment by harshalhonde21** [comment]
not button and all just want the default behaviour with scroll bar scrolling it should be very smooth not break means stop

**Comment by rahul-shrivastav** [comment]
So if inscroll down once it should get to end of page via smooth scroll and not stop?

**Comment by harshalhonde21** [comment]
yes great as for going to top there is button when scroll down at bottom right

**Comment by rahul-shrivastav** [comment]
Okay I will add that button to scroll down to end of page and then submit PR again

**Comment by harshalhonde21** [comment]
you don't understand the context actually what i want the scrool of mouse should be scroll it has smooth scrolling

**Comment by rahul-shrivastav** [comment]
Okay so no button required, only when I scroll down it directly get to end of page via smooth scroll

**Comment by harshalhonde21** [comment]
ya correct do it notify once

**Comment by rahul-shrivastav** [comment]
Okay I will do it asap

**Pull request closed without merging**
