### PR TITLE
#257 responsive done

### PR DESCRIPTION
**Pull request by Venkatknight2295**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
None
## Description
[Please include a brief description of the changes or features added]
made the logo in the menu align with all the resolutions
## Type of PR

- [x ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x ] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Venkatknight2295** [comment]
the changes are done please label and merge PR

**Comment by harshalhonde21** [comment]
image


you have disturb the tab view

**Comment by Venkatknight2295** [comment]
See Properly that Alignment is there from before Check my code i didnt even touch that part of the code Please review it and give me LEVEL 1 TAG

**Comment by Venkatknight2295** [comment]
IF YOU WANT ME TO CHANGE THAT I WILL MAKE OTHER ISSUE AND CHANGE IT

**Comment by harshalhonde21** [comment]
make change in this PR only after take latest pull i will directly add level2 label

**Comment by harshalhonde21** [comment]
already done

**Pull request closed without merging**
