### PR TITLE
Code  Check

### PR DESCRIPTION
**Pull request by Apurv7777**
Please review this code.

### CODE REVIEW

**Comment by Apurv7777** [comment]
I am getting error on new signup. Please help me in this.

**Comment by p00jitha** [comment]
@Apurv7777 did u added profilepic field in userSchema ?

**Comment by Apurv7777** [comment]
Yes

**Comment by Apurv7777** [comment]
Yes

**Comment by harshalhonde21** [comment]
Our signup form is running correct in live website see that

**Comment by Apurv7777** [comment]
It's right. But, adding these profile photo upload functionality,  It's not working. Don't know where I am stuck.
The Implementation is correct using multer .

**Comment by Apurv7777** [comment]
On checking the endpoint on Postman, it is giving error.
image
image

Why there is the error in this ?

**Comment by harshalhonde21** [comment]
> On checking the endpoint on Postman, it is giving error. image image
> 
> Why there is the error in this ?

Check this on your local url

**Pull request closed without merging**
