### PR TITLE
prduct is not exists then display not found

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
prduct is not exists then display not found #334
## Description
[Please include a brief description of the changes or features added]
prduct is not exists then display not found
## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@harshalhonde21 ,check it and merge it as per #334

**Comment by Varsani2520** [comment]
Hey @harshalhonde21 ,
please check it and merged it 
also add the label

**Comment by harshalhonde21** [comment]
the design of that card you add after dummy search which no match the product it is not matches the design of website do change like that

**Comment by Varsani2520** [comment]
Can you help me the which type of ui you want

**Comment by harshalhonde21** [comment]
it should match our whole theme

**Comment by Varsani2520** [comment]
Tell me you want to text type or img choose one

**Comment by Varsani2520** [comment]
Hey @harshalhonde21 , i change that as you say now check it and merged it also add the label as per issue no 334

**Comment by Varsani2520** [comment]
Hey @harshalhonde21 ,
check it and merged it as soon as possible

**Comment by sanjay-kv** [comment]
@harshalhonde21 let me know its the match you looking for

**Comment by harshalhonde21** [comment]
sorry for late reply @sanjay-kv  and @Varsani2520 it's very difficult to handle all the project single handed @sanjay-kv there is no mentor is assigned to make then is it my problem that you didn't assign the active mentor to my problem then also i handle the project very good but some misses

**Comment by harshalhonde21** [comment]
> Hey @harshalhonde21 , check it and merged it as soon as possible

@Varsani2520 I say you to match the image to ui so do that i will merge it

**Comment by Varsani2520** [comment]
@harshalhonde21 

i think this should match with ui
can you please tell me what kind of changes you need because i already completed empty state that match with your website ui

image

**Comment by harshalhonde21** [comment]
> @harshalhonde21
> 
> i think this should match with ui can you please tell me what kind of changes you need because i already completed empty state that match with your website ui
> 
> image

I mean just design the empty product image in adobe or canva and place there no need of text there the image should show that there is no product for this search

**Comment by Varsani2520** [comment]
@harshalhonde21 ,

how is it 
image

**Comment by harshalhonde21** [comment]
> @harshalhonde21 ,
> 
> how is it image

you want to show me on the real screen on the product page at website don't show like that

**Comment by Varsani2520** [comment]
ok

**Comment by Varsani2520** [comment]
@harshalhonde21 now you check it

**Comment by harshalhonde21** [comment]
> @harshalhonde21 now you check it

image


see the image is not visible check it and don't raise the changes if you are not done any thing

**Comment by Varsani2520** [comment]
@harshalhonde21 

check this , i update code

image

**Comment by Varsani2520** [comment]
@harshalhonde21 ,please merged it

**Comment by Varsani2520** [comment]
@harshalhonde21 ,give a response

**Comment by harshalhonde21** [comment]
> @harshalhonde21 ,give a response

don't spam frequently you will get the response

**Comment by harshalhonde21** [comment]
> @harshalhonde21
> 
> check this , i update code
> 
> image

its not looking well because of gif first off all dont use gif and see the below image it direactly understood that what image says

image


add like this image it will looks great

**Comment by Varsani2520** [comment]
ok

**Comment by Varsani2520** [comment]
Hey @harshalhonde21 ,i added as you say image instead of gif :
image

**Comment by harshalhonde21** [comment]
> Hey @harshalhonde21 ,i added as you say image instead of gif : image

dont add same image i say you make image like that which indicate that no item are availabe of this search

**Comment by Varsani2520** [comment]
ok I understood

**Comment by Varsani2520** [comment]
@harshalhonde21 
image

**Comment by harshalhonde21** [comment]
> @harshalhonde21 image

it is cart image the image can be added of reference like mart

**Comment by Varsani2520** [comment]
@harshalhonde21 

i update the empty state of products kindly check this and merge it

**Comment by harshalhonde21** [comment]
> @harshalhonde21
> 
> i update the empty state of products kindly check this and merge it

1. firstly there are conflicts in your PR resolve first 
2. change the image as it is cart image and there is no cart is is product showcase so research first what to add there

**Comment by harshalhonde21** [comment]
pr is closed as not follow the instruction do with removing of conflicts and raise another PR

**Pull request closed without merging**
