### PR TITLE
Home page not view properly in mobile view #172

### PR DESCRIPTION
**Pull request by kapilG0**
I fixed home screen and make responsive 
image
In mobile view first text was overlapping now it is not
and some other changes also has been done below also every thing not overlapping

### CODE REVIEW

**Comment by harshalhonde21** [comment]
There are conflicts in this branch always take pull first

**Comment by kapilG0** [comment]
> There are conflicts in this branch always take pull first

Ok I will keep in mind please let me know what can I do to resolve that

**Comment by harshalhonde21** [comment]
PUll the repo first and then make PR

**Comment by kapilG0** [comment]
> PUll the repo first and then make PR

Can you please guide me how can I do that I am new in open source and confuse with that how can I pull main repo code into forked repo and If I will do that then will my changes stay ?

**Comment by kapilG0** [comment]
> > PUll the repo first and then make PR
> 
> @harshalhonde21 Can you please guide me how can I do that I am new in open source and confuse with that how can I pull main repo code into forked repo and If I will do that then will my changes stay ?

@harshalhonde21 Should I sync forked repo and worked on that issue again then should raise pull request?

**Comment by harshalhonde21** [comment]
ya correct you should sync are you using github gui in vs code not using cmd??

**Comment by kapilG0** [comment]
> ya correct you should sync are you using github gui in vs code not using cmd??

I am more comfortable with GitHub gui sure I will sync my repo then I will raise pr

**Comment by kapilG0** [comment]
> > ya correct you should sync are you using github gui in vs code not using cmd??
> 
> I am more comfortable with GitHub gui sure I will sync my repo then I will raise pr

Hello @harshalhonde21 after sync my repo the functionality i was working is already implemented by some one else.

**Pull request closed without merging**
