### PR TITLE
Fixed :- #158 Arrow is overlapping with about and products in mobile view  and #159 making sidebar more attractive 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I changed the product and about section position in mobile view and changed position of arrow as well so that it can't be overlapped with these buttons in any view .
Here i am attaching the screenshots of my output .
Screenshot 2024-05-14 233745
Screenshot 2024-05-14 234654

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
If you want something else please let me know  .

**Comment by harshalhonde21** [comment]
image


the heading is under the navbar only

**Comment by harshalhonde21** [comment]
The heading of spectastyle at home page in overlapping in navbar fix that

**Comment by Ayushmaanagarwal1211** [comment]
ok i will do

**Pull request closed without merging**
