### PR TITLE
✔️Implemented a Feedback Page For the Website

### LINKED ISSUE #458: Feature🌟: Add a Feedback Form/Page to the Website
### Describe the feature

Hey @harshalhonde21 ,
I would like to add a feedback form/page to the website. 
Currently there is no Feedback form in the website, As 

Here's How will it work - 
- User Clicks on the "Give Feedback" button.
- System Displays the feedback form as a popup.
- User Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- Clicks the "Submit" button on the form.
- Displays a confirmation message indicating the feedback was submitted successfully.
- Closes the feedback form popup.

To improve user experience and gather valuable insights from visitors, i suggest to add a feedback form/page to the website. This form will allow users to provide their opinions, report issues, and suggest improvements directly.

For example like this:

image

I will add Link to the Feedback Page in the Website's Footer.
Could you please Assign me this issue ?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @harshalhonde21 ,
issue closes #458 

### What I Did 
1. **Added a "modal button"** to open the feedback form.
2. **Implemented a "tooltip"** for it to enhanced user experience.
3. Created a **"dedicated feedback form"** following the **website's color theme.**
4. **Made it "Responsive"** across all screen sizes.
5. **Implemented reset functionality** for the form.
6. **Added an alert for successful submission.**

**Please take a look -**

https://github.com/user-attachments/assets/69a0db34-755d-4b37-87ef-c8fa84f7e55e

## Type of PR
- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aslams2020** [comment]
@harshalhonde21 Please take a look.

**Comment by aslams2020** [comment]
@harshalhonde21 Please take a look

**Comment by harshalhonde21** [comment]
great @aslams2020 but there is one change add backend code for this to store in the db after this PR

**Comment by aslams2020** [comment]
@harshalhonde21 Should I Add Email sending functionality using emailJs which will send the feedbacks directly to ur email ? As I don't have any experience in backend,db till...

Also, Could u please update the level of this PR if possible.?

**Pull request merged**
