### PR TITLE
Redesigned logo (Fixed issue #281)

### PR DESCRIPTION
**Pull request by Anuja1227**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by harshalhonde21** [comment]
choose second logo but it should blend with navbar and do add that

**Comment by Anuja1227** [comment]
Okk i'll do that , but i'll be travelling for 2 days so I can start working
after that

**Comment by Anuja1227** [comment]
I had done the required changes asked by you should i raise the PR for it?

**Comment by harshalhonde21** [comment]
@Anuja1227 raise the pr and add that logo in the website corretly

**Comment by Anuja1227** [comment]
Ok

**Comment by Anuja1227** [comment]
I have raised new pr #398, please look into it, if its fine plz merge and label it, else if you want further changes , you can let me know.

**Comment by harshalhonde21** [comment]
already completed

**Pull request closed without merging**
