### PR TITLE
responsive logo

### LINKED ISSUE #431: BUG: Logo goes outside in responsive screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@harshalhonde21 

check this out,

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

BUG: Logo goes outside in responsive screen #431

close #431

## Description
[Please include a brief description of the changes or features added]

- responsive screen logo fixes

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@harshalhonde21 

kindly please check this and merge it

**Comment by harshalhonde21** [comment]
> @harshalhonde21
> 
> kindly please check this and merge it

image


see at this the logo is gone away of nav so do correct placing in all the pixels

**Comment by dhruv8433** [comment]
got it

**Comment by dhruv8433** [comment]
@harshalhonde21 

image

image

image

**Comment by harshalhonde21** [comment]
ohk that fine @dhruv8433

**Comment by dhruv8433** [comment]
Thank you :)

**Pull request merged**
