### PR TITLE
Fixing Product Detail Page

### PR DESCRIPTION
**Pull request by Apurv7777**
#255 

image

### CODE REVIEW

**Comment by harshalhonde21** [comment]
take the pull/sync first and then raise the pr because the previous functionality is disturb of viewing the product and also the product when click after should all pixel perfect responsive

**Comment by Apurv7777** [comment]
> take the pull/sync first and then raise the pr because the previous functionality is disturb of viewing the product and also the product when click after should all pixel perfect responsive

I have synced my code, already. Can you elaborate which functionality are getting harmed by my this PR ? Which functionality I have to be taken care?

**Comment by harshalhonde21** [comment]
If I scroll the product detail the whole page scroll down and the other product also clickable after one i active also

**Comment by Apurv7777** [comment]
> If I scroll the product detail the whole page scroll down and the other product also clickable after one i active also

Ok, What I understand from your comment .
- The page need not to be scroll, when any product is opened.
- User need not be able to select product other when other product is being displayed .

Am I correct ?

If yes, I will take care in next commit.

**Comment by Apurv7777** [comment]
### All the requested changes are done. Please review to this.

**Comment by harshalhonde21** [comment]
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/105191619/cf3c7a15-d81a-471e-b230-8cbcf

see what happing when i open the product it is going up while scroll achived the behaviour which is current website see there

**Comment by Apurv7777** [comment]
Sorry, but I am not able to see the image , you attached.

**Comment by Apurv7777** [comment]
#### Now, everything is done ?

**Comment by harshalhonde21** [comment]
now its great but what you want to do take the sync/pull first of current repo as there is merge conflicts then commit

**Comment by Apurv7777** [comment]
# Please merge it , if no further changes are required.

**Comment by Apurv7777** [comment]
# I request to the PA , please merge it , if not further changes are remaining.

**Comment by Apurv7777** [comment]
# Please merge this PR , if further changes are not requested

# In https://github.com/harshalhonde21/EcommerceSpectastyle/pull/13 https://github.com/harshalhonde21/EcommerceSpectastyle/pull/27

# Please add ***gssoc*** label and level label to both the PR's . Your efforts would be appreciated.

**Comment by Apurv7777** [comment]
@harshalhonde21 

# Please merge this PR , if further changes are not requested

# In https://github.com/harshalhonde21/EcommerceSpectastyle/pull/13 https://github.com/harshalhonde21/EcommerceSpectastyle/pull/27

#Please add gssoc label and level label to both the PR's . Your efforts would be appreciated.

**Comment by Apurv7777** [comment]
@harshalhonde21

**Comment by harshalhonde21** [comment]
done

**Comment by Apurv7777** [comment]
# Worst PA ever experienced. @harshalhonde21

**Pull request closed without merging**
