### PR TITLE
Completed UI Updates + Responsiveness [UI Change]

### PR DESCRIPTION
**Pull request by aayushwrld**
I have completed the changes I suggested for the UI and also made the UI completely responsive.

Kindly merge this request as it is a major UI change.

[Issue 48](https://github.com/harshalhonde21/EcommerceSpectastyle/issues/48)

### CODE REVIEW

**Comment by aayushwrld** [comment]
@harshalhonde21 Please check and merge, as alot of files have been changed!

**Comment by officeneerajsaini** [comment]
@aayushwrld I reviewed your PR, and you did amazing work. However, there are some components that, if you fix them, we will have a good UI for the entire website.

Screenshot from 2024-05-11 10-59-21

**Comment by officeneerajsaini** [comment]
Screenshot from 2024-05-11 11-12-33

**Comment by aayushwrld** [comment]
> Screenshot from 2024-05-11 11-12-33

@officeneerajsaini Thank you! Can you please mention the page for where the issue if happening for the footer?

**Comment by officeneerajsaini** [comment]
> @aayushwrld I reviewed your PR, and you did amazing work. However, there are some components that, if you fix them, we will have a good UI for the entire website.
> 
> Screenshot from 2024-05-11 10-59-21

this one on the home page there some content hide ...shoe image ,
another one in footer section , and in different screen size like in tab screen there navbar element hover .

**Comment by aayushwrld** [comment]
> this one on the home page there some content hide ...shoe image , another one in footer section , and in different screen size like in tab screen there navbar element hover .

I'll look into it thank you!

**Comment by officeneerajsaini** [comment]
@aayushwrld 
And one mistake you made in this PR is that you made the PR from your main branch. It's not a good idea. Next time, create a separate branch for the PR and make the PR from your new branch, not directly from the main branch. That's why we use GitHub for version control, so we can see code branches separately. But you did a great job.

**Comment by aayushwrld** [comment]
> @aayushwrld And one mistake you made in this PR is that you made the PR from your main branch. It's not a good idea. Next time, create a separate branch for the PR and make the PR from your new branch, not directly from the main branch. That's why we use GitHub for version control, so we can see code branches separately. But you did a great job.

Alright! I will take care of that from next time. Thank you so much! @officeneerajsaini

**Pull request closed without merging**
