### PR TITLE
Revert "Update the UI of Login and signup page with the Captcha funct…

### PR DESCRIPTION
**Pull request by harshalhonde21**
…ionality"

### CODE REVIEW

**Comment by harshalhonde21** [comment]
@Apurv7777  there are some error the RECAPTCHA is not showing there

**Comment by harshalhonde21** [comment]
> @Apurv7777 there are some error the RECAPTCHA is not showing there

image

**Comment by Apurv7777** [comment]
This is because of the VITE_SITE_KEY in .env.local. Please setup your SITE_KEY by using steps mentioned last and replaced it to solve the problem.

**Comment by Apurv7777** [comment]
It's just a simple process :

1) Go to [Google reCAPTCHA](https://www.google.com/recaptcha/about/)
2) Go to Admin Console.
3) Signup/Login , if required.
4) Give any label you want.
image
5) Select reCAPTCHA type: Challenge(v2) and select "I'm not a robot" Checkbox.
6) Add domain of your website .
E.g.) https://spectastyle.vercel.app/
7) Click Submit.
8) Copy the SITE KEY and replace the VITE_SITE_KEY.

**Comment by Apurv7777** [comment]
> > @Apurv7777 there are some error the RECAPTCHA is not showing there
> 
> image
> 
> what to do for that

This is because I have deleted the SITE_KEY linked to my account.

**Comment by harshalhonde21** [comment]
Can you add the key I am providing the key to you??

**Comment by harshalhonde21** [comment]
6LczqtcpAAAAANy0GMH976MUbjUAYAIYV6ZSeTeN

this is the key please add that I create one more PR

**Pull request merged**
