### PR TITLE
dockerized the app

### PR DESCRIPTION
**Pull request by vedantterse**
## Related Issue 
solves #285 
## Description

I dockerized the app making it easier to setup locally
## Type of PR

- [x] Feature enhancement

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
I also updated the README.md and added steps to setup the docker

### CODE REVIEW

**Comment by vedantterse** [comment]
please ignore the ( ' ) Apostrophe changes in the commit

**Comment by harshalhonde21** [comment]
@vedantterse please give brief how to do steps after merging this particular stuff

**Comment by harshalhonde21** [comment]
> please ignore the ( ' ) Apostrophe changes in the commit

why you change the env code in server

**Comment by vedantterse** [comment]
> > please ignore the ( ' ) Apostrophe changes in the commit
> 
> why you change the env code in server

I fixed that index.js minor changes , now there are  no changes in that file

**Comment by harshalhonde21** [comment]
> > > please ignore the ( ' ) Apostrophe changes in the commit
> > 
> > 
> > why you change the env code in server
> 
> I fixed that index.js minor changes , now there are no changes in that file

give brief explanation for the this whole pr actually I am new to devops term so please tell when i will do docker compose up then where the image of nodejs will create

**Comment by vedantterse** [comment]
> > > > please ignore the ( ' ) Apostrophe changes in the commit
> > > 
> > > 
> > > why you change the env code in server
> > 
> > 
> > I fixed that index.js minor changes , now there are no changes in that file
> 
> give brief explanation for the this whole pr actually I am new to devops term so please tell when i will do docker compose up then where the image of nodejs will create



ok got it! 


Image Creation:
 When you execute docker-compose up, Docker Compose will build the necessary images based on the configurations in the Dockerfile. These images will be created and managed by Docker.
 You can view and manage these images through Docker Desktop, where you will see the Node.js image created as part of this process.
 
 
Benefits of Dockerizing the App

 Docker ensures that everyone working on the project uses the same versions of Node.js and other dependencies, regardless of their local environment.
 and  also  Simplified Setup.

**Comment by harshalhonde21** [comment]
> > > > > please ignore the ( ' ) Apostrophe changes in the commit
> > > > 
> > > > 
> > > > why you change the env code in server
> > > 
> > > 
> > > I fixed that index.js minor changes , now there are no changes in that file
> > 
> > 
> > give brief explanation for the this whole pr actually I am new to devops term so please tell when i will do docker compose up then where the image of nodejs will create
> 
> ok got it!
> 
> Image Creation: When you execute docker-compose up, Docker Compose will build the necessary images based on the configurations in the Dockerfile. These images will be created and managed by Docker. You can view and manage these images through Docker Desktop, where you will see the Node.js image created as part of this process.
> 
> Benefits of Dockerizing the App
> 
> Docker ensures that everyone working on the project uses the same versions of Node.js and other dependencies, regardless of their local environment. and also Simplified Setup.
> 
> It's just a handy feature to have in, and it has no conflict with the development.

great @vedantterse looks great, but for this I will show to my friends who is devops engineer if he looks great to pr i will merge it my tommorow

**Comment by vedantterse** [comment]
> > > > > > please ignore the ( ' ) Apostrophe changes in the commit
> > > > > 
> > > > > 
> > > > > why you change the env code in server
> > > > 
> > > > 
> > > > I fixed that index.js minor changes , now there are no changes in that file
> > > 
> > > 
> > > give brief explanation for the this whole pr actually I am new to devops term so please tell when i will do docker compose up then where the image of nodejs will create
> > 
> > 
> > ok got it!
> > Image Creation: When you execute docker-compose up, Docker Compose will build the necessary images based on the configurations in the Dockerfile. These images will be created and managed by Docker. You can view and manage these images through Docker Desktop, where you will see the Node.js image created as part of this process.
> > Benefits of Dockerizing the App
> > Docker ensures that everyone working on the project uses the same versions of Node.js and other dependencies, regardless of their local environment. and also Simplified Setup.
> > It's just a handy feature to have in, and it has no conflict with the development.
> 
> great @vedantterse looks great, but for this I will show to my friends who is devops engineer if he looks great to pr i will merge it my tommorow

Sure !, let me know if any changes are required!

**Comment by harshalhonde21** [comment]
> > > > > > > please ignore the ( ' ) Apostrophe changes in the commit
> > > > > > 
> > > > > > 
> > > > > > why you change the env code in server
> > > > > 
> > > > > 
> > > > > I fixed that index.js minor changes , now there are no changes in that file
> > > > 
> > > > 
> > > > give brief explanation for the this whole pr actually I am new to devops term so please tell when i will do docker compose up then where the image of nodejs will create
> > > 
> > > 
> > > ok got it!
> > > Image Creation: When you execute docker-compose up, Docker Compose will build the necessary images based on the configurations in the Dockerfile. These images will be created and managed by Docker. You can view and manage these images through Docker Desktop, where you will see the Node.js image created as part of this process.
> > > Benefits of Dockerizing the App
> > > Docker ensures that everyone working on the project uses the same versions of Node.js and other dependencies, regardless of their local environment. and also Simplified Setup.
> > > It's just a handy feature to have in, and it has no conflict with the development.
> > 
> > 
> > great @vedantterse looks great, but for this I will show to my friends who is devops engineer if he looks great to pr i will merge it my tommorow
> 
> Sure !, let me know if any changes are required!

hey @vedantterse your PR is great no doubt but keep patience as my devops team is busy right now will review shortly

**Pull request merged**
