### PR TITLE
Update UI for Login and Signup Pages

### PR DESCRIPTION
**Pull request by Apurv7777**
### Overview
This PR updates the user interface for the login and signup pages to enhance the overall user experience and improve visual consistency.

### Changes Made
- Refactored layout for improved responsiveness 
- Refactored profile picture input on Signup Page

### Reasons for Changes
The UI changes were implemented to create a more cohesive and user-friendly experience for our platform's login and signup process. By aligning with brand guidelines and improving accessibility, we aim to increase user engagement and satisfaction.

### Impact
- These changes should not introduce any breaking changes or compatibility issues.
- The updated UI has been tested across various browsers to ensure a consistent experience.
- Automated tests for form validation and layout responsiveness have been added to maintain code quality.

### Screenshots
image
image

### Reviewer Requests
Please review the accessibility improvements and ensure compatibility with a range of devices and screen sizes.

### Additional Notes
- Feedback and suggestions for further enhancements are welcome.

### CODE REVIEW

**Comment by harshalhonde21** [comment]
this is very small contribution you can add the captch functionality, then we will merge it into main.

look upon the [Issue](https://github.com/harshalhonde21/EcommerceSpectastyle/issues/12) this issue

**Comment by Apurv7777** [comment]
> this is very small contribution you can add the captch functionality, then we will merge it into main.
> 
> look upon the [Issue](https://github.com/harshalhonde21/EcommerceSpectastyle/issues/12) this issue, I want to great functionality

Which functionality you are talking about ?

**Comment by Apurv7777** [comment]
> this is very small contribution you can add the captch functionality, then we will merge it into main.
> 
> look upon the [Issue](https://github.com/harshalhonde21/EcommerceSpectastyle/issues/12) this issue, I want to great functionality

Which functionality you are talking about ? "captch" ?

**Comment by harshalhonde21** [comment]
> I am not able to understand that. Please elaborate.

image


like this generate the captcha always unique and compare our captcha with user captcha if correct then authenticate the user

**Comment by Apurv7777** [comment]
Ok, Captcha, I am not able to understang because of the typo "captch". My Bad !!

**Comment by Apurv7777** [comment]
I'd like to suggest replacing our current text-based CAPTCHA with **Google reCAPTCHA**. 

 **Google reCAPTCHA** employs advanced risk analysis techniques to keep automated software from engaging in abusive activities on our site. By leveraging Google's vast resources and constant updates, we can stay one step ahead of malicious bots and spam attacks.

I understand that making changes to our current setup may require some adjustments, but I believe the benefits of adopting Google reCAPTCHA far outweigh the initial implementation effort. It's a proactive step towards safeguarding our website and ensuring a positive experience for our users.

**Comment by harshalhonde21** [comment]
> I'd like to suggest replacing our current text-based CAPTCHA with **Google reCAPTCHA**.
> 
> **Google reCAPTCHA** employs advanced risk analysis techniques to keep automated software from engaging in abusive activities on our site. By leveraging Google's vast resources and constant updates, we can stay one step ahead of malicious bots and spam attacks.
> 
> I understand that making changes to our current setup may require some adjustments, but I believe the benefits of adopting Google reCAPTCHA far outweigh the initial implementation effort. It's a proactive step towards safeguarding our website and ensuring a positive experience for our users.

Great idea @Apurv7777 go ahead with this and this is time to merge this update but listen one thing we thing functionality the code base of website should not be affect

**Comment by Apurv7777** [comment]
I have successfully integrated Google reCAPTCHA.

image

**Comment by Apurv7777** [comment]
I'm not able to figure out which checks are failing . Can you help me out ?

**Comment by harshalhonde21** [comment]
What is purpose of add the file of .env.local and you didn't install the react-google-recaptcha library as npm just install the dependencies correct then raise the PR once again

**Comment by Apurv7777** [comment]
.env.local is for setting the Google reCAPTCHA site key .

You can get yours from : 
[Google reCAPTCHA](https://www.google.com/recaptcha/about/)

**Comment by harshalhonde21** [comment]
Great update brother is Level 2 is good for your PR??

Can you explain how you executed the reCaptcha functionality what is use of key is any value is going to the your account of RECAPTCHA ??

I will merge it after you explain it I am very curious about this updated

**Comment by Apurv7777** [comment]
I have just putted my SECRET_KEY linked to my account for testing purpose. Thus, you can change it later on .
The use of SECRET_KEY is just to verify the request initiator for Google reCAPTCHA.

**Comment by harshalhonde21** [comment]
> I have just putted my SITE_KEY linked to my account for testing purpose. Thus, you can change it later on of your's. The use of SITE_KEY is just to verify the request initiator for Google reCAPTCHA.

Is any affect is will not to connect your SITE_KEY??

**Comment by Apurv7777** [comment]
No. You can easily create yours.

**Comment by harshalhonde21** [comment]
> No. You can easily create yours.

If your RECAPTCH is there so is any problem that I am asking like security anything??

**Comment by harshalhonde21** [comment]
> > No. You can easily create yours.
> 
> If your RECAPTCH is there so is any problem that I am asking like security anything??

Is any user data is going to your account??

**Comment by Apurv7777** [comment]
Totally No. It is just for testing purpose. I am also going to delete this SITE_KEY from my account after successfull integration.

**Comment by harshalhonde21** [comment]
> Totally No. It is just for testing purpose. I am also going to delete this SITE_KEY from my account after successfull integration.

Which type of integration are you saying about??

**Comment by Apurv7777** [comment]
If any security breach is there, then the **vercel** would also not allowed this in checks.

**Comment by Apurv7777** [comment]
> > Totally No. It is just for testing purpose. I am also going to delete this SITE_KEY from my account after successfull integration.
> 
> Which type of integration are you saying about??

Means after this merging of PR. I am going to delete this key and I advised you to create a new SITE_KEY , I have also provided the link to create.

**Comment by harshalhonde21** [comment]
> If any security breach is there, then the **vercel** would also not allowed this in checks.

Ya cool, great update @Apurv7777 nice contribution.

**Comment by Apurv7777** [comment]
This SITE_KEY is just like "JWT_SECRET".

**Comment by harshalhonde21** [comment]
> > > Totally No. It is just for testing purpose. I am also going to delete this SITE_KEY from my account after successfull integration.
> > 
> > 
> > Which type of integration are you saying about??
> 
> Means after this merging of PR. I am going to delete this key and I advised you to create a new SITE_KEY , I have also provided the link to create.

I didn't have that much time to develop the application because of my internship give another idea to do that.

**Comment by harshalhonde21** [comment]
> This SITE_KEY is just like "JWT_SECRET".

Okh now understand great did you provide the SITE_KEY in .env and add the .env in gitignore

**Comment by Apurv7777** [comment]
It's just a simple process : 
1) Go to [Google reCAPTCHA](https://www.google.com/recaptcha/about/)
2) Go to Admin Console.
3) Signup/Login , if required.
4) Give any label you want.
image
5) Select reCAPTCHA type: Challenge(v2) and select "I'm not a robot" Checkbox.
6) Add domain of your website .
    E.g.) https://spectastyle.vercel.app/
7) Click Submit.

**Comment by Apurv7777** [comment]
> > This SITE_KEY is just like "JWT_SECRET".
> 
> Okh now understand great did you provide the SITE_KEY in .env and add the .env in gitignore

Yes, it's in the ".env.local" file

**Comment by Apurv7777** [comment]
I have deleted SITE_KEY from my account, that's why the reCAPTCHA may not works. You can paste your SITE_KEY for successfull working. If you are still stuck, please let me know.

**Comment by Apurv7777** [comment]
Please add gssoc label to this.

**Comment by Apurv7777** [comment]
### Do assign necessary labels to this.

**Comment by Apurv7777** [comment]
# Please add gssoc label to this.

**Comment by sanjay-kv** [comment]
@harshalhonde21 i can see this contributor spend much time on this PR. kindly give labels. + add me into the repo to further handle the repo issues. @harshalhonde21

**Pull request merged**
